Service, controller, test for schedule
marlexxa/Dance-School-Management-System pull request #31
Opened 2021-03-11 19:11 UTC by jkilar

2021-03-11 19:15 UTC, DariuszKny requested changes

2021-03-11 19:15 UTC, DariuszKny commented on src/schedule/entities/schedule.entity.ts
> +    required: true,
Brak stworzonej relacji

2021-03-11 19:15 UTC, DariuszKny commented on src/schedule/dto/update-schedule.dto.ts
> +  lessons: [];
Wyczytałem w dokumentacji że tutaj klasa nie musi mieć żadnych parametrów, bo samo z siebie to wynika jak rozszerzamy ten PartialType

2021-03-11 19:15 UTC, DariuszKny commented on src/schedule/schedule.controller.ts
Brakuje endpointu po wyszukiwaniu po lekcji

2021-03-13 21:16 UTC, marlexxa reviewed
1. Dodałam komentarze, jednak na razie ciężko będzie to zmienić dopóki nie ma modułu Lesson, możesz ewentualnie zmienić i zakomentować tam gdzie będą błędy.
 2. Testy chyba też trzeba będzie przerobić, ewentualnie dodać nowe, żeby sprawdzić jak działają na istniejących lekcji, żeby nie można było do schedule dodać takiej, której nie ma w bazie

2021-03-13 21:16 UTC, marlexxa commented on src/schedule/dto/create-schedule.dto.ts
> +  lessons: string[];
tutaj trzeba połączyć z `LessonInterface` zamiast string[]

2021-03-13 21:16 UTC, marlexxa commented on src/schedule/entities/schedule.entity.ts
> +  lessonId: string[];
tutaj jako `lessons` żeby było zgodnie z innymi zmiennymi i importujemy schemat `Lesson` z `lesson/entities`

2021-03-13 21:16 UTC, marlexxa commented on src/schedule/interfaces/schedule.interface.ts
> +  lessons: string[];
podobnie jak w `CreateLessonDto`  importujemy `LessonInterface`

2021-03-13 21:16 UTC, marlexxa commented on src/schedule/schedule.module.ts
> +  ],
wydaje mi się, że tutaj jeszcze byłoby trzeba zaimportować schemat lekcji, ale nie jestem pewna

2021-03-13 21:16 UTC, marlexxa commented on src/schedule/schedule.service.ts
> +      schedule.lessons.forEach((lessonId) => {
tutaj trzeba będzie to sprawdzać po id z bazy danych, które dodaje mongoose, czyli np. `forEach((lesson) => if (lesson._id ==id)` , to `_id` jest właśnie tym które tworzy mongoose

2021-03-13 21:16 UTC, marlexxa commented on test/schedule.e2e-spec.ts
> +describe('USER', () => {
tutaj SCHEDULE

2021-03-15 21:38 UTC, DariuszKny approved these changes

2021-03-16 11:31 UTC, Chlip approved these changes

2021-03-16 12:11 UTC, merged